# Generated by Django 4.2.7 on 2023-11-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuxSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_raining', models.BooleanField()),
            ],
        ),
    ]
