# Generated by Django 4.2.7 on 2023-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynopticAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
