# Generated by Django 4.2.7 on 2023-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_api', '0002_synopticanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('date_br', models.DateTimeField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('wind_velocity', models.FloatField()),
                ('wind_direction', models.CharField(max_length=255)),
                ('wind_direction_degrees', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SynopticAnalysis',
        ),
    ]
