# Generated by Django 4.2.7 on 2023-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_api', '0003_weatherforecast_delete_synopticanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_direction_degrees',
            field=models.FloatField(null=True),
        ),
    ]
